annotations:
  category: Tools
  images: |
    - name: kubectl
      image: us-east1-docker.pkg.dev/testkube-cloud-372110/testkube/kubectl:1.35.1
  licenses: Apache-2.0
apiVersion: v2
appVersion: "1.35.1"
description: Testkube kubectl image for Kubernetes operations.
maintainers:
- name: Testkube
  email: support@testkube.io
  url: https://github.com/kubeshop/testkube-thirdparty-artifacts
name: kubectl
sources:
- https://github.com/kubeshop/testkube-thirdparty-artifacts/tree/main/kubectl
- https://kubernetes.io/docs/reference/kubectl/
version: 1.35.1-0

