annotations:
  category: Database
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r33
    - name: postgres-exporter
      image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r1
    - name: postgresql
      image: us-east1-docker.pkg.dev/testkube-cloud-372110/testkube/testkube-postgresql:18-debian-12
  licenses: Apache-2.0
apiVersion: v2
appVersion: 18.0.0
description: Testkube helm chart to deploy Postgresql instance.
home: https://testkube.io
dependencies:
  - name: common
    version: 2.26.0
    repository: "file://../../common"
maintainers:
  - name: Testkube
    url: https://github.com/kubeshop/testkube-thirdparty-artifacts
name: postgresql
sources:
  - https://github.com/kubeshop/testkube-thirdparty-artifacts/tree/main/postgresql
  - https://github.com/bitnami/containers/blob/main/bitnami/postgresql/18/debian-12/Dockerfile
version: 0.1.1
